import * as THREE from 'three';
import {chapterOneMap} from './maps/chapter-one.mjs';
import {compileMap} from './block-map.mjs';
import {SCREENING_CENTER,SCREENING_ROOMS} from './maps/screening-center.mjs';
import {buildScreeningScene} from './screening-scene.js';
import {moveCircle} from './rules.mjs';
import {selectInteraction} from './interaction.mjs';
import {hasLineOfSight} from './enemies.mjs';
import {createInventory} from './economy.mjs';
import {createProgression} from './progression.mjs';
import {WEAPONS,chapterLoadout,magazine} from './weapons.mjs';
import {createWeaponSession,discoverArmory,fireWeapon,reloadWeapon,switchWeapon,tickWeaponSession,sessionStats} from './weapon-session.mjs';
import {createAudioEngine} from './audio-engine.js';
import {createWeaponAudio} from './weapon-audio.js';
import {readTransfer,hydrateTransfer} from './chapter-transfer.mjs';
import {createChapterOneGame} from './chapter-one-game.js';
const transferred=await readTransfer();
const $=id=>document.getElementById(id),scene=new THREE.Scene();scene.background=new THREE.Color(0x101e2b);scene.fog=new THREE.Fog(0x101e2b,55,115);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.domElement.id='world';renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));document.body.prepend(renderer.domElement);
const camera=new THREE.OrthographicCamera(-24,24,16,-16,.1,160);
scene.add(new THREE.HemisphereLight(0xd0e6ef,0x324350,2));const moon=new THREE.DirectionalLight(0xa8c6e2,1.5);moon.position.set(-20,40,10);scene.add(moon);
const player=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.38,.75,4,8),new THREE.MeshStandardMaterial({color:0xbed188}));body.position.y=.9;player.add(body);const pack=new THREE.Mesh(new THREE.BoxGeometry(.55,.6,.24),new THREE.MeshStandardMaterial({color:0x354a4b}));pack.position.set(0,.85,.35);player.add(pack);scene.add(player);
const rainGeometry=new THREE.BufferGeometry(),rainPositions=new Float32Array(300*6);rainGeometry.setAttribute('position',new THREE.BufferAttribute(rainPositions,3));const rain=new THREE.LineSegments(rainGeometry,new THREE.LineBasicMaterial({color:0x84a1b4,transparent:true,opacity:.23}));scene.add(rain);
const keys=new Set();let map,visual,state='playing',elapsed=0,visited=new Set(),inspected=new Set(),lastZone=null,session,shooting=false,muted=false,lastAudio=null,lastNoise=null,flash=0,practiceTargets=[],targetMeshes=[],tracers=[],campaign=null;
const pointer=new THREE.Vector2(),ray=new THREE.Raycaster(),ground=new THREE.Plane(new THREE.Vector3(0,1,0),-.7),aim=new THREE.Vector3();
const soundscape=createAudioEngine(camera,scene,()=>muted,()=>obstacles());const weaponAudio=createWeaponAudio(camera,player,()=>muted,{engine:soundscape,getEnvironment:()=>map?.zoneAt(player.position)?.audioZone}),gunModel=new THREE.Mesh(new THREE.BoxGeometry(.18,.2,1.1),new THREE.MeshStandardMaterial({color:0xb6b291})),muzzle=new THREE.Mesh(new THREE.SphereGeometry(.15,8,6),new THREE.MeshBasicMaterial({color:0xffda84}));gunModel.position.set(.24,.9,.55);muzzle.position.set(.24,.9,1.16);muzzle.visible=false;player.add(gunModel,muzzle);
function weaponSound(event,gun){lastAudio=weaponAudio.play(event,gun,{reloadSeconds:session.reloadTimer})??{event,profile:gun.soundProfile??'standard',muted:true};if(event==='fire'){lastNoise={weapon:session.bag.equipped,x:player.position.x,z:player.position.z,radius:gun.soundRadius,time:elapsed};window.dispatchEvent(new CustomEvent('weapon-noise',{detail:{...lastNoise}}));campaign?.hear(lastNoise);flash=.07;}}
const obstacles=()=>[...map.obstacles(),...visual.colliders];
const movementObstacles=()=>[...obstacles(),...(campaign?.enemies??[]).filter(e=>e.hp>0).map(e=>({x:e.x,z:e.z,w:e.radius*2,d:e.radius*2})),...practiceTargets.filter(t=>session.bag.weapons.includes('sg12')&&t.hp>0).map(t=>({x:t.x,z:t.z,w:t.radius*2,d:t.radius*2}))];
function renderWeapons(){for(let i=tracers.length-1;i>=0;i--)if(!session.projectiles.some(p=>p.id===tracers[i].userData.id)){const mesh=tracers.splice(i,1)[0];scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();}
 for(const p of session.projectiles){let mesh=tracers.find(m=>m.userData.id===p.id);if(!mesh){mesh=new THREE.Mesh(new THREE.BoxGeometry(.045,.045,.5),new THREE.MeshBasicMaterial({color:0xffd891}));mesh.userData.id=p.id;scene.add(mesh);tracers.push(mesh);}mesh.position.set(p.x,.7,p.z);mesh.rotation.y=Math.atan2(p.vx,p.vz);}
 practiceTargets.forEach((t,i)=>{const mesh=targetMeshes[i];mesh.position.set(t.x,.75,t.z);mesh.visible=session.bag.weapons.includes('sg12')&&t.hp>0;mesh.material.color.set(t.damageTaken>0?0xb66d63:0x8ab5c4);});muzzle.visible=flash>0;
}
function disposeWorld(){if(!visual)return;scene.remove(visual.root);const geometry=new Set(),materials=new Set();visual.root.traverse(o=>{if(o.geometry)geometry.add(o.geometry);if(o.material)materials.add(o.material);});for(const g of geometry)g.dispose();for(const m of materials){m.map?.dispose();m.dispose();}}
function build(){weaponAudio.cancelReload();campaign?.dispose();campaign=null;$('chapterOverlay').hidden=true;$('chapterMission').hidden=true;disposeWorld();for(const mesh of tracers){scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();}tracers=[];weaponAudio.mute();map=compileMap(transferred?chapterOneMap():SCREENING_CENTER);visual=buildScreeningScene(scene,map);state='playing';elapsed=0;visited=new Set();inspected=new Set();keys.clear();shooting=false;lastAudio=null;lastNoise=null;flash=0;lastZone=null;const entry=transferred?hydrateTransfer(transferred):{bag:createInventory(),progression:createProgression(),hp:100};const bag=entry.bag;if(!transferred)bag.reserves.shells=18;chapterLoadout(bag,1);session=createWeaponSession(bag,entry.progression,weaponSound,hit=>{if(!hit.target)soundscape.cue('impact',hit);else if(!campaign)soundscape.cue('hit',hit);});
 const target=map.spawns.find(s=>s.id==='armory-target');practiceTargets=[{id:target.id,x:target.x,z:target.z,radius:.65,hp:500,maxHp:500,damageTaken:0}];targetMeshes=practiceTargets.map(t=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(.8,1.5,.45),new THREE.MeshStandardMaterial({color:0x8ab5c4}));mesh.position.set(t.x,.75,t.z);visual.root.add(mesh);return mesh;});
 if(transferred){practiceTargets=[];targetMeshes.forEach(m=>m.visible=false);targetMeshes=[];visual.markers.get('armory-target').visible=false;campaign=createChapterOneGame({map,scene,camera,visual,session,player,hp:entry.hp,freeze,obstacles,audioCue:soundscape.cue});}const start=map.spawns.find(s=>s.kind==='player');player.position.set(start.x,0,start.z);camera.position.set(start.x,28,start.z+23);camera.lookAt(start.x,0,start.z);$('note').hidden=true;$('status').textContent='สำรวจด่าน — ค้นหา SG-12 ที่ Security Armory';updateZone();updateUI();}
function setPaused(paused){if(!['playing','paused'].includes(state))return;state=paused?'paused':'playing';keys.clear();shooting=false;weaponAudio.mute();soundscape.setActive(state==='playing');$('pauseOverlay').hidden=!paused;$('pause').textContent=paused?'เล่นต่อ / ESC':'พัก / ESC';updateUI();}
function changeDoor(door){if(door.locked){soundscape.cue('locked',door);$('status').textContent='ประตูล็อก';return;}
 const dx=Math.max(0,Math.abs(player.position.x-door.x)-(door.vertical?.14:map.doorWidth/2)),dz=Math.max(0,Math.abs(player.position.z-door.z)-(door.vertical?map.doorWidth/2:.14));
 if(door.open&&Math.hypot(dx,dz)<.46){$('status').textContent='ถอยออกจากช่องประตูก่อนปิด';return;}
 soundscape.cue('door',door);map.setDoorOpen(door.id,!door.open);visual.doorMeshes.get(door.id).visible=!door.open;$('status').textContent=door.open?'เปิดประตูแล้ว':'ปิดประตูแล้ว';}
function current(){if(state!=='playing')return null;return selectInteraction(player.position,[
 ...(campaign?.targets()??[]),
 ...map.doors.map(d=>({id:d.id,position:d,distance:1.9,available:true,action:d.open?'ปิดประตู':'เปิดประตู',activate:()=>changeDoor(d)})),
 ...map.spawns.filter(s=>s.kind==='objective'||s.kind==='loot').map(s=>({id:s.id,position:s,distance:1.7,priority:1,available:(campaign?campaign.canInspect(s.id):(s.id!=='armory-target'||session.bag.weapons.includes('sg12')))&&hasLineOfSight(player.position,s,obstacles()),action:s.id==='armory'&&!session.bag.weapons.includes('sg12')?'เก็บ SG-12 Tactical Shotgun':s.label,activate:()=>{inspected.add(s.id);visual.markers.get(s.id).material.color.set(0x93b0b7);if(s.id==='armory')discoverArmory(session,player.position,s,obstacles());if(s.id==='armory-target'){const t=practiceTargets[0];Object.assign(t,{x:s.x,z:s.z,hp:t.maxHp,damageTaken:0,lastImpulseShot:null});} $('note').textContent=s.id==='armory'&&campaign?'เก็บ SG-12 แล้ว — Secondary / Shells / แมกกาซีน 6 นัด':s.id==='armory'?'เก็บ SG-12 แล้ว — 6 นัด / ใช้ Shells · เป้าฝึกอยู่ในทางเดิน Security · ไม่มี EXP หรือรางวัล':s.note;$('note').hidden=false;$('status').textContent='ตรวจแล้ว: '+s.label;}}))
 ]);}
function updateZone(){const zone=map.zoneAt(player.position);if(!zone||zone.blockId===lastZone)return;lastZone=zone.blockId;visited.add(lastZone);const room=SCREENING_ROOMS[lastZone];$('roomName').textContent=room.name;$('roomDescription').textContent=room.description;$('visitedCount').textContent=visited.size+' / '+map.blocks.length;if(!campaign&&visited.size===10)$('status').textContent='สำรวจครบ 10 พื้นที่ — ประตู Doge City ยังปิดอยู่';}
function updateUI(){const target=current();$('prompt').hidden=!target;if(target)$('prompt').textContent='[ E ] '+target.action;$('pauseOverlay').hidden=state!=='paused';$('pause').textContent=state==='paused'?'เล่นต่อ / ESC':'พัก / ESC';const gun=WEAPONS[session.bag.equipped];$('fieldWeaponName').textContent=gun.name;$('fieldAmmo').textContent=magazine(session.bag);$('fieldCapacity').textContent=gun.magazineSize;$('fieldReserve').textContent=session.bag.reserve+' '+gun.ammoType;$('fieldReload').textContent=session.reloadTimer>0?'กำลังรีโหลด '+session.reloadTimer.toFixed(1)+' วินาที':'R: รีโหลด · F: เปลี่ยนปืน · เมาส์: เล็ง / ยิง';gunModel.material.color.set(gun.color);gunModel.scale.z=gun.slot==='sidearm'?.45:1;}
function minimap(){const canvas=$('minimap'),ctx=canvas.getContext('2d'),scale=3.25,ox=70,oz=15,px=x=>ox+x*scale,pz=z=>oz+z*scale;ctx.clearRect(0,0,canvas.width,canvas.height);
 for(const block of map.blocks){for(const cell of block.cells){ctx.fillStyle=visited.has(block.id)?'#658a91':'#2d4655';ctx.fillRect(px(cell.x*6-2.9),pz(cell.z*6-2.9),5.8*scale,5.8*scale);}const center=block.cells[0];ctx.fillStyle='#d4e4e4';ctx.font='8px Arial';ctx.textAlign='center';ctx.fillText({highway:'HWY',waiting:'WAIT',screening:'SCREEN',security:'SEC',medical:'MED',quarantine:'Q',isolation:'ISO',control:'CTRL',bus:'BUS',gate:'GATE',city:'CITY'}[block.id],px(center.x*6),pz(center.z*6)+3);}
 for(const d of map.doors){ctx.strokeStyle=d.open?'#add284':'#d39772';ctx.lineWidth=2;ctx.beginPath();if(d.vertical){ctx.moveTo(px(d.x),pz(d.z-1.2));ctx.lineTo(px(d.x),pz(d.z+1.2));}else{ctx.moveTo(px(d.x-1.2),pz(d.z));ctx.lineTo(px(d.x+1.2),pz(d.z));}ctx.stroke();}
 ctx.fillStyle='#defb88';ctx.beginPath();ctx.arc(px(player.position.x),pz(player.position.z),3.8,0,Math.PI*2);ctx.fill();}
window.addEventListener('keydown',event=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space',...(campaign?['Tab']:[])].includes(event.code))event.preventDefault();if(event.code==='Escape'&&!event.repeat){if(state==='playing'||state==='paused')setPaused(state==='playing');return;}if(state!=='playing')return;if(campaign){ray.setFromCamera(pointer,camera);ray.ray.intersectPlane(ground,aim);}if(!event.repeat&&campaign?.input(event.code,aim)){updateUI();return;}if(event.code==='KeyE'&&!event.repeat){current()?.activate();updateUI();}else if(event.code==='KeyR'&&!event.repeat)reloadWeapon(session);else if(event.code==='KeyF'&&!event.repeat)switchWeapon(session);else keys.add(event.code);});window.addEventListener('keyup',event=>keys.delete(event.code));window.addEventListener('blur',()=>{if(state==='playing')setPaused(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')setPaused(true);});
window.addEventListener('mousemove',event=>pointer.set(event.clientX/innerWidth*2-1,1-event.clientY/innerHeight*2));renderer.domElement.addEventListener('mousedown',event=>{if(event.button===0&&state==='playing')shooting=true;});window.addEventListener('mouseup',()=>shooting=false);$('fieldMute').onclick=()=>{muted=!muted;weaponAudio.mute();if(!muted)soundscape.unlock();$('fieldMute').textContent=muted?'เสียง: ปิด':'เสียง: เปิด';};
$('pause').onclick=()=>setPaused(state==='playing');$('resume').onclick=()=>setPaused(false);$('reset').onclick=build;
function freeze(next){state=next;keys.clear();shooting=false;weaponAudio.mute();soundscape.setActive(state==='playing');updateUI();}
function resize(){const aspect=innerWidth/innerHeight,halfHeight=Math.max(15,23/aspect);camera.left=-halfHeight*aspect;camera.right=halfHeight*aspect;camera.top=halfHeight;camera.bottom=-halfHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);}
window.addEventListener('resize',resize);build();resize();let last=performance.now();
renderer.setAnimationLoop(now=>{let dt=Math.min(.05,(now-last)/1000);last=now;const audioDt=dt;if(state==='playing'){while(dt>0&&state==='playing'){const step=Math.min(1/60,dt),dx=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft')),dz=Number(keys.has('KeyS')||keys.has('ArrowDown'))-Number(keys.has('KeyW')||keys.has('ArrowUp')),length=Math.hypot(dx,dz)||1;moveCircle(player.position,dx/length*sessionStats(session).movementSpeed*step,dz/length*sessionStats(session).movementSpeed*step,.45,movementObstacles(),Infinity);ray.setFromCamera(pointer,camera);ray.ray.intersectPlane(ground,aim);if(Math.hypot(aim.x-player.position.x,aim.z-player.position.z)>.01)player.rotation.y=Math.atan2(aim.x-player.position.x,aim.z-player.position.z);tickWeaponSession(session,step,obstacles(),[...(session.bag.weapons.includes('sg12')?practiceTargets:[]),...(campaign?.enemies??[])]);weaponAudio.syncReload(session.reloadTimer,WEAPONS[session.bag.equipped]);campaign?.tick(step);if(shooting)fireWeapon(session,player.position,aim);flash=Math.max(0,flash-step);elapsed+=step;dt-=step;}updateZone();}
 camera.position.set(player.position.x,28,player.position.z+23);camera.lookAt(player.position.x,0,player.position.z);rain.visible=map.zoneAt(player.position)?.audioZone==='OUTDOOR';
 for(let i=0;i<300;i++){const x=((i*17.3)%44)-22,z=((i*9.7)%40)-20,y=10-((elapsed*13+i*.71)%10);rainPositions.set([player.position.x+x,y,player.position.z+z,player.position.x+x-.08,y+.55,player.position.z+z-.12],i*6);}rainGeometry.attributes.position.needsUpdate=true;renderWeapons();updateUI();campaign?.updateUI();minimap();soundscape.update(audioDt,{playing:state==='playing',position:player.position,environment:map.zoneAt(player.position)?.audioZone});renderer.render(scene,camera);
});
Object.defineProperty(window,'screeningCenter',{get:()=>({state,elapsed,player:{x:player.position.x,z:player.position.z},zone:map.zoneAt(player.position),visited:[...visited],inspected:[...inspected],interaction:current()?.id??null,complete:visited.size===10,walkable:map.isWalkable(player.position)&&!visual.colliders.some(o=>Math.hypot(player.position.x-Math.max(o.x-o.w/2,Math.min(player.position.x,o.x+o.w/2)),player.position.z-Math.max(o.z-o.d/2,Math.min(player.position.z,o.z+o.d/2)))<.45-1e-6),doors:map.doors.map(d=>({...d})),blocks:map.blocks.map(b=>({id:b.id,type:b.type,rotation:b.rotation,name:SCREENING_ROOMS[b.id].name,cells:b.cells.map(c=>({...c}))})),spawns:map.spawns.map(s=>({...s,cell:[...s.cell],offset:[...s.offset]})),obstacles:obstacles(),mode:transferred?'campaign':'preview',campaign:campaign?.snapshot()??null,progression:{...session.progression,ranks:{...session.progression.ranks}},activeEnemies:campaign?.enemies.filter(e=>e.hp>0).length??0,cityGateOpen:campaign?.snapshot().gateOpen??false,weapon:{ammo:magazine(session.bag),reloadTimer:session.reloadTimer,stats:sessionStats(session),shots:session.shots,pellets:session.pellets,hits:session.hits,projectiles:session.projectiles.map(p=>({...p})),lastSound:session.lastSound?{...session.lastSound}:null,lastNoise:lastNoise?{...lastNoise}:null,lastAudio:lastAudio?{...lastAudio}:null,muted},inventory:{...session.bag,weapons:[...session.bag.weapons],magazines:{...session.bag.magazines},reserves:{...session.bag.reserves},loadout:{...session.bag.loadout},upgrades:{...session.bag.upgrades},recoil:{...session.bag.recoil},grenades:{...session.bag.grenades}},practiceTargets:practiceTargets.map(t=>{const p=new THREE.Vector3(t.x,.7,t.z).project(camera);return {...t,screen:{x:(p.x+1)*innerWidth/2,y:(1-p.y)*innerHeight/2}}})})});







window.addEventListener('keydown',()=>soundscape.unlock(),{capture:true});window.addEventListener('pointerdown',()=>soundscape.unlock(),{capture:true});
Object.defineProperty(window,'deadZoneAudio',{get:()=>({scene:soundscape.snapshot(),weapon:weaponAudio.snapshot()})});
