import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {compileMap} from '../block-map.mjs';
import {SCREENING_CENTER} from '../maps/screening-center.mjs';
const require=createRequire(import.meta.url),puppeteer=require(process.env.PUPPETEER_MODULE||'puppeteer');
const browser=await puppeteer.launch({headless:true,executablePath:process.env.CHROME_PATH,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader'],defaultViewport:{width:1440,height:900}}),page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const read=()=>page.evaluate(()=>window.screeningCenter),sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function walk(point){for(const axis of ['x','z'])for(let tries=0;tries<8;tries++){const s=await read(),delta=point[axis]-s.player[axis];if(Math.abs(delta)<.18)break;const positive=delta>0,key=axis==='x'?(positive?'d':'a'):(positive?'s':'w'),code='Key'+key.toUpperCase();await page.keyboard.down(key);try{await page.waitForFunction((axis,target,positive,code)=>{const s=window.screeningCenter,d=s.doors.find(d=>d.id===s.interaction);if((positive?s.player[axis]>=target-.06:s.player[axis]<=target+.06)||(d&&!d.open)){window.dispatchEvent(new KeyboardEvent('keyup',{code,bubbles:true}));return true;}return false;},{timeout:10000},axis,point[axis],positive,code);}finally{await page.keyboard.up(key);}const s2=await read(),door=s2.doors.find(d=>d.id===s2.interaction);if(door&&!door.open)await page.keyboard.press('e');}const end=await read();assert.ok(Math.hypot(end.player.x-point.x,end.player.z-point.z)<.3,'Arrival '+JSON.stringify({point,player:end.player,interaction:end.interaction}));}
async function shootOne(){const before=(await read()).weapon.shots;await page.mouse.down();try{await page.waitForFunction(n=>window.screeningCenter.weapon.shots>n,{timeout:4000},before);}finally{await page.mouse.up();}return await read();}
try{
 await mkdir('artifacts/phase8',{recursive:true});await page.goto('http://127.0.0.1:5173/screening-center.html',{waitUntil:'networkidle0'});await page.waitForFunction(()=>window.screeningCenter?.state==='playing');const start=await read();assert.deepEqual(start.inventory.loadout,{primary:'m4x',secondary:null,sidearm:'vx9'});assert.equal(start.inventory.weapons.includes('sg12'),false);await page.keyboard.press('e');assert.equal((await read()).inventory.weapons.includes('sg12'),false);
 const map=compileMap(SCREENING_CENTER),armory=map.spawns.find(s=>s.id==='armory');for(const p of map.findPath(start.player,armory,{allowClosed:true}))await walk(p);assert.equal((await read()).interaction,'armory');await page.keyboard.press('e');const found=await read();assert.equal(found.inventory.equipped,'sg12');assert.equal(found.weapon.ammo,6);assert.equal(found.inventory.reserves.shells,18);assert.equal(found.weapon.stats.soundRadius,45);assert.equal(found.weapon.stats.reloadSeconds,3.2);await page.screenshot({path:'artifacts/phase8/discovery.png'});
 await walk({x:-6,z:42});await walk({x:-6,z:44});const t=(await read()).practiceTargets[0];await page.mouse.move(t.screen.x,t.screen.y);const fired=await shootOne();assert.equal(fired.weapon.ammo,5);assert.equal(fired.weapon.pellets,8);await page.waitForFunction(()=>window.screeningCenter.weapon.hits>0);const hit=await read();assert.ok(hit.practiceTargets[0].damageTaken>25);assert.ok(Math.hypot(hit.practiceTargets[0].x-t.x,hit.practiceTargets[0].z-t.z)>.5);assert.equal(hit.weapon.lastNoise.radius,45);assert.equal(hit.weapon.lastAudio.profile,'sg12');assert.ok(Number.isInteger(hit.weapon.lastAudio.variant));await page.screenshot({path:'artifacts/phase8/impact.png'});
 await page.keyboard.press('r');const reloading=await read();assert.ok(reloading.weapon.reloadTimer>2.7);await page.keyboard.press('Escape');const frozen=await read();await sleep(350);assert.deepEqual(await read(),frozen);await page.click('#resume');await page.keyboard.press('f');assert.equal((await read()).weapon.reloadTimer,0);assert.equal((await read()).inventory.reserves.shells,18);await page.keyboard.press('f');await page.keyboard.press('f');assert.equal((await read()).weapon.ammo,5);
 await page.keyboard.press('r');await page.waitForFunction(()=>window.screeningCenter.weapon.reloadTimer===0&&window.screeningCenter.weapon.ammo===6,{timeout:25000});assert.equal((await read()).inventory.reserves.shells,17);
 await walk({x:-6,z:42});await walk({x:-12,z:42});await page.keyboard.press('e');assert.equal((await read()).inventory.reserves.shells,17,'Duplicate armory visit cannot refill reserve');
 await page.click('#fieldMute');await page.mouse.move(720,200);const muted=await shootOne();assert.equal(muted.weapon.ammo,5);assert.equal(muted.weapon.lastNoise.radius,45);assert.equal(muted.weapon.lastAudio.muted,true);
 const emptyStart=(await read()).weapon.shots;await page.mouse.down();try{await page.waitForFunction(n=>window.screeningCenter.weapon.shots>=n+5&&window.screeningCenter.weapon.reloadTimer>0,{timeout:30000},emptyStart);}finally{await page.mouse.up();}assert.equal((await read()).weapon.ammo,0);await page.waitForFunction(()=>window.screeningCenter.weapon.reloadTimer===0,{timeout:25000});assert.equal((await read()).inventory.reserves.shells,11);assert.equal((await read()).weapon.ammo,6);
 await page.setViewport({width:800,height:600});await page.screenshot({path:'artifacts/phase8/small.png'});await writeFile('artifacts/phase8/weapon-checkpoint.json',JSON.stringify(await read(),null,2));await page.click('#reset');const reset=await read();assert.equal(reset.inventory.weapons.includes('sg12'),false);assert.equal(reset.inventory.reserves.shells,18);assert.equal(reset.weapon.shots,0);assert.equal(reset.weapon.reloadTimer,0);assert.equal(reset.weapon.projectiles.length,0);assert.deepEqual(errors,[]);console.log('SG12_PASS: physical pickup, eight pellets per shell, practice impact/impulse, unique audio/noise, reload freeze/cancel/complete, magazine preservation, finite ammo, mute, duplicate pickup and reset.');
}catch(error){const s=await read();if(s)await writeFile('artifacts/phase8/failure.json',JSON.stringify(s,null,2));throw error;}finally{await browser.close();}
