import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const require=createRequire(import.meta.url), puppeteer=require(process.env.PUPPETEER_MODULE||'puppeteer');
const browser=await puppeteer.launch({headless:true,executablePath:process.env.CHROME_PATH,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader'],defaultViewport:{width:1280,height:800}});
const page=await browser.newPage(),errors=[];
page.on('pageerror',error=>errors.push(error.message));
const read=()=>page.evaluate(()=>window.zombieShooter);
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
try{
 await page.goto('http://127.0.0.1:5173',{waitUntil:'networkidle0'});
 await page.waitForFunction(()=>window.zombieShooter?.state==='ready');
 await page.click('#start');
 await page.keyboard.down('a');
 await page.waitForFunction(()=>{if(window.zombieShooter.player.x<=-3){window.dispatchEvent(new KeyboardEvent('keyup',{code:'KeyA'}));return true;}return false;},{timeout:10000});
 await page.keyboard.up('a');
 await page.keyboard.down('w');
 await page.waitForFunction(()=>window.zombieShooter.player.z<=16.46,{timeout:10000});
 await sleep(350);
 await page.keyboard.up('w');
 const blocked=await read();
 assert.ok(blocked.player.z>=16.449 && blocked.player.z<=16.46,'Player stops at actual lab cover, including radius: '+JSON.stringify(blocked.player)+'');
 assert.ok(blocked.core.obstacles.some(o=>o.x===-3&&o.z===15));
 await page.keyboard.down('s');
 await page.waitForFunction(()=>{if(window.zombieShooter.player.z>=18){window.dispatchEvent(new KeyboardEvent('keyup',{code:'KeyS'}));return true;}return false;},{timeout:10000});
 await page.keyboard.up('s');
 await page.keyboard.down('a');
 await page.waitForFunction(()=>{if(window.zombieShooter.player.x<=-5){window.dispatchEvent(new KeyboardEvent('keyup',{code:'KeyA'}));return true;}return false;},{timeout:10000});
 await page.keyboard.up('a');
 assert.equal((await read()).core.interaction,'crate-0');
 assert.equal(await page.$eval('#lootPrompt',e=>e.hidden),false);
 const before=await read();
 await page.keyboard.press('e');
 const collected=await read();
 assert.ok(collected.inventory.materials>before.inventory.materials);
 assert.equal(collected.core.interaction,null);
 assert.equal(await page.$eval('#lootPrompt',e=>e.hidden),true);
 await page.keyboard.press('e');
 assert.equal((await read()).inventory.materials,collected.inventory.materials,'Used crate does not reward twice');
 // Measure normalized diagonal movement in simulation time, not wall-clock timing.
 const diagonalStart=await read();
 await page.keyboard.down('d');await page.keyboard.down('s');
 await page.waitForFunction(start=>window.zombieShooter.core.elapsed-start>=.22,{},diagonalStart.core.elapsed);
 await page.keyboard.up('d');await page.keyboard.up('s');
 const diagonalEnd=await read();
 const distance=Math.hypot(diagonalEnd.player.x-diagonalStart.player.x,diagonalEnd.player.z-diagonalStart.player.z);
 const expected=(diagonalEnd.core.elapsed-diagonalStart.core.elapsed)*diagonalStart.combatStats.movementSpeed;
 assert.ok(Math.abs(distance-expected)<.16,'Diagonal movement does not gain extra speed');
 await page.keyboard.down('d');
 await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
 await page.keyboard.up('d');
 const paused=await read();
 assert.equal(paused.state,'paused');
 await sleep(250);
 assert.deepEqual((await read()).player,paused.player);
 assert.equal((await read()).core.elapsed,paused.core.elapsed);
 await page.click('#start');
 await sleep(200);
 assert.deepEqual((await read()).player,paused.player,'Resume does not retain held movement keys');
 await page.keyboard.press('Escape');
 const snapshot=await read();
 await page.setViewport({width:960,height:640});
 await page.waitForFunction(()=>Math.abs(window.zombieShooter.core.camera.right/window.zombieShooter.core.camera.top-innerWidth/innerHeight)<0.00001,{timeout:10000});
 const resized=await read();
 assert.equal(resized.state,'paused');
 assert.deepEqual(resized.inventory,snapshot.inventory);
 assert.deepEqual(resized.progression,snapshot.progression);
 assert.equal(resized.core.camera.right/resized.core.camera.top,await page.evaluate(()=>innerWidth/innerHeight));
 assert.ok(Math.abs(resized.core.camera.x-resized.player.x*.22)<.001);
 assert.ok(Math.abs(resized.core.camera.z-(resized.player.z*.22+30))<.001);
 assert.match(await page.$eval('#hpText',e=>e.textContent),new RegExp(Math.ceil(resized.hp)+' / '+resized.maxHp+' HP'));
 await mkdir(new URL('../artifacts/phase2/',import.meta.url),{recursive:true});
 await page.screenshot({path:new URL('../artifacts/phase2/core.png',import.meta.url).pathname.replace(/^\/(\w:)/,'$1')});
 assert.deepEqual(errors,[]);
 console.log('CORE_TEST_PASS: lab collision, normalized movement, E prompt/action, one-use loot, blur/pause, cleared input, camera resize and HUD');
}finally{await browser.close();}
