import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const require=createRequire(import.meta.url),puppeteer=require(process.env.PUPPETEER_MODULE||'puppeteer'),browser=await puppeteer.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader'],defaultViewport:{width:1200,height:800}}),page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const read=()=>page.evaluate(()=>window.audioFixture),sleep=ms=>new Promise(r=>setTimeout(r,ms));
try{await mkdir('artifacts/phase10',{recursive:true});await page.goto('http://127.0.0.1:5173/tests/audio-harness.html',{waitUntil:'networkidle0'});await page.waitForFunction(()=>window.audioFixture);assert.equal((await read()).engine.unlocked,false);await page.click('#unlock');await page.waitForFunction(()=>window.audioFixture.engine.ambient.length===1);
 for(const zone of ['OUTDOOR','SMALL_ROOM','LARGE_ROOM','UNDERGROUND','WAREHOUSE']){await page.select('#zone',zone);await page.waitForFunction(z=>window.audioFixture.engine.zone===z&&window.audioFixture.engine.ambient.some(a=>a.zone===z&&a.volume>.005),{},zone);await page.click('#fire');assert.equal((await read()).weapon.last.environment,zone);assert.ok((await read()).weapon.last.rate>=.97&&(await read()).weapon.last.rate<=1.03);}
 await page.waitForFunction(()=>window.audioFixture.weapon.assetLoaded>0);await page.click('#fire');assert.equal((await read()).weapon.last.source,'local-wav');await page.click('#dry');assert.equal((await read()).weapon.last.event,'dry');
 await page.click('#left');let data=await read();assert.equal(data.engine.lastCue.position.x,-4);assert.ok(data.engine.voices.every(v=>v.positional));assert.equal(data.engine.listener.y,1.65);await page.click('#right');assert.equal((await read()).engine.lastCue.type,'runner');await page.click('#cover');assert.equal((await read()).engine.lastCue.occluded,true);await page.click('#impact');assert.equal((await read()).engine.lastCue.occluded,false,'Impact on a visible wall face stays audible');const dropped=(await read()).engine.dropped;await page.click('#far');assert.equal((await read()).engine.dropped,dropped+1);await page.click('#limit');assert.ok((await read()).engine.voiceCount<=24);
 await page.click('#reload');assert.equal((await read()).weapon.last.event,'reload_out');await page.click('#pause');const paused=await read();await sleep(250);assert.equal((await read()).reload,paused.reload);assert.equal((await read()).engine.voiceCount,0);assert.deepEqual((await read()).engine.ambient,[]);assert.deepEqual((await read()).weapon.reload,paused.weapon.reload);await page.click('#pause');await page.waitForFunction(()=>window.audioFixture.reload===0,{timeout:12000});const cues=(await read()).weapon.history.map(e=>e.event);assert.ok(cues.includes('reload_in'));assert.ok(cues.includes('reload_slide'));
 await page.click('#reload');await page.click('#cancel');const cancelled=await read();await sleep(2200);assert.equal((await read()).weapon.reload,null);assert.deepEqual((await read()).weapon.history,cancelled.weapon.history,'Cancelled reload has no delayed cues');
 await page.click('#mute');const muted=await read();await page.click('#fire');await page.click('#left');assert.equal((await read()).engine.played,muted.engine.played);assert.deepEqual((await read()).engine.ambient,[]);await page.click('#mute');await page.waitForFunction(()=>window.audioFixture.engine.ambient.length>0);await page.click('#pause');await sleep(1000);assert.equal((await read()).engine.voiceCount,0);assert.deepEqual(errors,[]);assert.deepEqual((await read()).weapon.assetErrors,[]);await writeFile('artifacts/phase10/audio-engine-checkpoint.json',JSON.stringify(await read(),null,2));console.log('AUDIO_PASS: local AudioLoader, five acoustic zones, positional/occluded/range-limited cues, bounded voices, staged/cancelled reload, pause, mute and cleanup.');
}finally{await browser.close();}
