import {mkdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {WEAPONS} from '../weapons.mjs';
import {synthesizeWeaponSound} from '../weapon-sound.mjs';
import {seededNoise} from '../audio-profiles.mjs';
// Reproducible local PCM assets. All source audio is generated by this repository.
const sampleRate=24000,manifest=[];let seed=1;
for(const [id,gun] of Object.entries(WEAPONS))for(const event of ['fire_0','fire_1','fire_2','fire_3','reload_out','reload_in','reload_slide','dry','equip']){
 const fire=event.startsWith('fire_'),variant=fire?Number(event.at(-1)):0,{samples}=synthesizeWeaponSound(gun,fire?'fire':event,variant,sampleRate,seededNoise(seed++));
 const wav=Buffer.alloc(44+samples.length*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(sampleRate,24);wav.writeUInt32LE(sampleRate*2,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(samples.length*2,40);samples.forEach((v,i)=>wav.writeInt16LE(Math.round(Math.max(-1,Math.min(1,v))*32767),44+i*2));
 const file='sounds/weapons/'+id+'/'+event+'.wav';await mkdir('sounds/weapons/'+id,{recursive:true});await writeFile(file,wav);manifest.push({file,sha256:createHash('sha256').update(wav).digest('hex'),sampleRate,frames:samples.length});
}
await writeFile('sounds/manifest.json',JSON.stringify({generator:'tools/generate-audio.mjs',license:'Original procedural audio generated in this project',files:manifest},null,2)+'\n');console.log('Generated '+manifest.length+' local WAV assets.');
